-- AlterTable
ALTER TABLE "Menu" ADD COLUMN     "hpp" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "marginNominal" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "marginPersen" DECIMAL(5,2) NOT NULL DEFAULT 0;
